name: Blindar e Publicar Site

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Injetar Token Secreto no HTML
        run: |
          sed -i "s/__TELEGRAM_TOKEN__/${{ secrets.TELEGRAM_BOT_TOKEN }}/g" index.html

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
